"""empty message

Revision ID: 0583cef1e5f9
Revises: 54996639b065
Create Date: 2021-09-10 09:38:09.148303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0583cef1e5f9'
down_revision = '54996639b065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Authors', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE "Authors" SET completed=False WHERE completed IS NULL;')
    # ### end Alembic commands ###

    op.alter_column('Authors', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Authors', 'completed')
    # ### end Alembic commands ###
