"""empty message

Revision ID: 0d7877cacc04
Revises: d669b4d33ebe
Create Date: 2021-09-21 13:19:02.540239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7877cacc04'
down_revision = 'd669b4d33ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('yob', sa.Integer(), nullable=True))
    op.drop_column('authors', 'year_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('year_of_birth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('authors', 'yob')
    # ### end Alembic commands ###
