"""empty message

Revision ID: 54996639b065
Revises: 23466b33aecf
Create Date: 2021-09-10 09:27:50.291945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54996639b065'
down_revision = '23466b33aecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'completed')
    # ### end Alembic commands ###
