"""empty message

Revision ID: 6467e65419e9
Revises: 0d7877cacc04
Create Date: 2021-09-21 13:31:09.125941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6467e65419e9'
down_revision = '0d7877cacc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'yob',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.execute('UPDATE authors SET yob = 1000 WHERE yob is NULL;')

    op.alter_column('authors', 'yob', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'yob',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
