"""empty message

Revision ID: b78cabeffa65
Revises: e00ea20a124f
Create Date: 2021-09-10 10:26:18.085274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78cabeffa65'
down_revision = 'e00ea20a124f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
