"""empty message

Revision ID: d669b4d33ebe
Revises: f61cb996cb30
Create Date: 2021-09-21 12:51:49.968016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd669b4d33ebe'
down_revision = 'f61cb996cb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('year_of_birth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'year_of_birth')
    # ### end Alembic commands ###
