"""empty message

Revision ID: f61cb996cb30
Revises: b78cabeffa65
Create Date: 2021-09-20 11:13:52.873028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61cb996cb30'
down_revision = 'b78cabeffa65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
